name: Minima Jekyll CI

on:
  push:
    paths:
      - 'minima/**'
  pull_request:
    paths:
      - 'minima/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-version: '2.6.9'
          cache: 'bundler'

      - name: Install dependencies
        working-directory: minima
        run: bundle install --jobs 4 --retry 3

      - name: Build Minima site
        working-directory: minima
        run: bundle exec jekyll build --destination ../1zZ
